# options:
#   machineType: 'E2_HIGHCPU_8'
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/superb-joy-343701/new-rayuan-api', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/superb-joy-343701/new-rayuan-api']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'new-rayuan-api', '--image', 'gcr.io/superb-joy-343701/new-rayuan-api', '--region', 'asia-southeast2', '--port', '80']
images:
- gcr.io/superb-joy-343701/new-rayuan-api