swagger: '2.0'
info:
  description: API to rate handwriting.
  version: 1.0.0
  title: rayuan-ic
host: rayuan-ic.apigateway.rayuan-api.cloud.goog
x-google-backend:
         address: https://rayuan-ic-api-ljq2gnzcga-et.a.run.app
schemes:
- https
- http
produces:
  - application/json
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
paths:
  /prediction:
     post:
       summary: Uploads a file.
       operationId: rateHandwriting
       consumes:
         - multipart/form-data
       parameters:
         - in: formData
           name: imagefile
           type: file
           description: The image to be rated.
       responses:
         '200':
           description: Successfully rate a handwriting
           schema:
             type: string