openapi: "3.0.3"
info:
  title: Rayuan Handwriting RESTful API
  description: An API used to evaluate handwriting.
  contact:
    name: API Support
    email: muhammadfahmi250@gmail.com
  version: "1.0"
servers:
  - url: https://rayuan-rate-74y1l31t.ts.gateway.dev
    description: Production server
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: key
paths:
  /prediction:
    post:
      tags: ["Handwriting's"]
      summary: Identify the value of a handwriting
      description: Getting and predicting the value of a handwriting
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          'text/plain; charset=utf-8':
            schema:
              type: string
            examples:
              'Base64 encoded handwriting image example':
                value: '/9j/4AAQSkZJRgABAgEASABIAAD/4R8yRXhpZgAATU0AKgAAAAgACwEPAAIAAAAJAAAAkgEQAAIAAAAPAAAAmwESAAMAAAABAAEAAAEaAAUAAAABAAAAqgEbAAUAAAABAAAAsgEoAAMAAAABAAIAAAExAAIAAAAbAAAAugEyAAIAAAAUAAAA1QITAAMAAAABAAIAAIKYAAIAAAAFAAAA6YdpAAQAAAABAAAA8AA...'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  label:
                    type: string
                    description: Image assessment value
                  certainty:
                    type: string
                    description: Image assessment certainty value
              examples:
                'Success example':
                  description: Example of a succeed request
                  value:
                    {
                      label: "Great",
                      certainty: "0.972467312"
                    }
